import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Banner from "../components/Banner";
// This js document renders components on screen

// Next JS has a built-in router, which index.js is a starting point. index.js points to the /index.js

export default function Home() {
    return (
        // this is tailwind CSS that has utility classes.
        <div className="">
            <Head>
                <title>George's Airbnb</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {/*Header*/}
            <Header />
            {/*Banner*/}
            <Banner />
        </div>
    )
}
